services:
  libremdb:
    container_name: libremdb
    image: ghcr.io/zyachel/libremdb:latest
    ports:
      - "3004:3000"
    env_file: .env
    depends_on:
      - libremdb-redis
    restart: always
    user: 65534:65534 # equivalent to the nobody user
    read_only: true
    tmpfs:
      - /opt/app/.next/cache/:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - libremdb

  libremdb-redis:
    container_name: libremdb_redis
    image: redis
    restart: always
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    cap_drop:
      - ALL
    networks:
      - libremdb

networks:
  libremdb:
