services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - SERVERPORT=51820
      # Change this to your local CIDR
      - HOME_CIDR=192.168.0.0/24
    volumes:
      - ./wg.conf:/config/wg_confs/wg0.conf
      - /lib/modules:/lib/modules
    ports:
      # We open the transmission web UI port here as we're going to use this
      # containers network for that container.
      - 51820:51820/udp
      - 51824:51824/udp
      - 9091:9091
  transmission:
    image: linuxserver/transmission:latest
    restart: always
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      PUID: 1000
      PGID: 1000
      # Change this to host(s) you want to access from
      # WHITELIST: "*.*.*.*"
    volumes:
      - ./config:/config
      - /tank/media/_downloads:/downloads
      - /tank/media/_watch:/watch
